#
# nixsh — every shell on every machine, declared.
#
# ONE MODULE FOR EVERY SHELL, fish included: the ADOPTION pattern (how to take over a config file
# a vendor package or years of hand-editing already owns) is identical for bash, zsh and fish --
# /etc/bash.bashrc and a hand-edited ~/.bashrc are the same situation fish's fish_variables is --
# so splitting fish into its own module would just mean two homes for the same logic.
#
# WHAT IS SHARED AND WHAT IS NOT. This is the whole design, and getting it wrong is the obvious
# trap. Shared: environment variables and PATH, because the only difference between shells there
# is `set -gx` versus `export`. NOT shared: aliases, functions, completions -- fish is not POSIX,
# so a generic alias DSL rendering to three syntaxes would render to three syntaxes BADLY. Those
# stay per-shell, deliberately unabstracted.
#
# NIX OWNS CONFIG, THE SYSTEM OWNS THE BINARY. See lib/shells.nix.
{ config, lib, ... }:
let
  cfg = config.nixsh;
  catalogue = import ../lib/shells.nix { };
  enabled = lib.filter (s: cfg.${s}.enable) (lib.attrNames catalogue);

  # The shared layer, rendered into each shell's own syntax.
  envFor = shell:
    let c = catalogue.${shell}; in
    lib.concatStringsSep "\n" (
      (lib.mapAttrsToList c.exportFmt cfg.environment.variables)
      ++ (map c.pathFmt cfg.environment.path)
    );

  mkShell = name: {
    enable = lib.mkEnableOption "declarative ${name} configuration (config only -- the binary comes from the system)";

    interactiveInit = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Literal ${name} run at interactive startup. Not translated to any other shell; write ${name} syntax.";
    };

    aliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Aliases for ${name}. Per-shell on purpose: alias syntax and semantics differ enough between fish and POSIX shells that sharing them would be a lie.";
    };
  };
in
{
  options.nixsh = {
    fish = mkShell "fish" // {
      # The one piece of fish state home-manager genuinely cannot own, because fish writes it
      # itself at runtime into fish_variables. Declaring it here makes it reproducible instead
      # of a file nobody remembers creating.
      universalVariables = lib.mkOption {
        type = lib.types.attrsOf lib.types.str;
        default = { };
        description = "fish universal variables (`set -U`). Applied idempotently at shell startup, since fish owns fish_variables itself and home-manager cannot write it.";
      };
    };
    bash = mkShell "bash";
    zsh = mkShell "zsh";

    environment = {
      variables = lib.mkOption {
        type = lib.types.attrsOf lib.types.str;
        default = { };
        description = "Environment variables, rendered into every enabled shell's own export syntax. THE shared layer -- if a setting differs per shell, it does not belong here.";
      };
      path = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        description = "Directories prepended to PATH in every enabled shell.";
      };
    };

    loginShell = lib.mkOption {
      type = lib.types.nullOr (lib.types.enum (lib.attrNames catalogue));
      default = null;
      description = ''
        Which shell is the login shell. null leaves it alone.

        Recorded rather than enforced: changing a login shell is `chsh` against /etc/passwd, which
        is system state this module has no business rewriting from under a running session. What
        this gives you is the declared intent, and something to check drift against.
      '';
    };

    # ── Computed ──────────────────────────────────────────────────────────────────────────────
    archPackages = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      readOnly = true;
      description = "Enabled shells as pacman names, for the host's reconciler. The BINARIES -- config is written separately by the home-manager backend.";
    };

    rcFiles = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      readOnly = true;
      description = "Generated rc content, keyed by home-relative path. The home-manager backend writes these; a consumer can inspect them without applying anything.";
    };
  };

  config = {
    nixsh.archPackages = map (s: catalogue.${s}.arch) enabled;

    nixsh.rcFiles = lib.listToAttrs (map
      (s: lib.nameValuePair catalogue.${s}.rcPath (lib.concatStringsSep "\n" (lib.filter (x: x != "") [
        "# Generated by nixsh. Do not edit."
        (envFor s)
        (lib.concatStringsSep "\n" (lib.mapAttrsToList (n: v: ''alias ${n}="${v}"'') cfg.${s}.aliases))
        (lib.optionalString (s == "fish") (lib.concatStringsSep "\n"
          (lib.mapAttrsToList (n: v: ''set -q ${n}; or set -U ${n} "${v}"'') cfg.fish.universalVariables)))
        cfg.${s}.interactiveInit
      ])))
      enabled);
  };
}
